### PR TITLE
1. Fixed a minor bug in distance computation

### PR DESCRIPTION
**Pull request by JosephArnold**
2. Removed OpenMP pragma in calculation of reordered points as that may lead to race condition.

### CODE REVIEW

**Comment by Markus-Goetz** [comment]
While I do see the addition of the template parameter T in the region_query as correct, I have difficulties seen the correctness of the removal of the #pragma on the reordering. This is an out-of-place, i.e. in different memory, rearrangement. This should not cause any race conditions. Am I missing something?

**Comment by JosephArnold** [comment]
In line 200, const Cell cell = m_cells[i], multiple points will have the same cell number right? So, 
'const size_t copy_to = locator.first + (offsets[cell]++)' will lead to a race condition as the different threads could have the same value of 'cell' which would eventually lead to a race condition during the update of (offsets[cell]  right?

**Comment by Markus-Goetz** [comment]
No it should not, as the set of iteration indices are disjoint

**Comment by JosephArnold** [comment]
The iteration indices are disjoint but values in 'm_cells' could be the same right? Enabling openmp resulted in segmentation fault later in the recover_initial_order() function as 'reordered_points' end up having values that are beyond the array index bound. I observed this only for the remote sensing dataset.

**Pull request merged**
